server:
  port: 8081
# Configuración personalizada
# URL base para PokeAPI
# Ajusta si necesitas un buffer más grande
skaro:
  pokeapi:
    base-uri: https://pokeapi.co/api/v2/
    max-buffer-size: 565000